baseURL = 'https://example.org/'
languageCode = 'fr-be'
title = 'Carnets lunaires'
theme = 'PaperMod'
[taxonomies]
  tag = 'tags'
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags/'
    weight = 20
[security]
  enableInlineShortcodes = true
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'