baseURL = 'https://noninomnom.github.io/carnetslunaires/'
languageCode = 'fr-be'
timezone = 'Europe/Brussels'
title = 'Carnets lunaires'
theme = 'PaperMod'
summaryLength = 120

[taxonomies]
  tag = 'tags'
[menus]
  [[menus.main]]
    name = 'Recherche'
    pageRef = '/search'
    weight = 1
  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 2
[security]
  enableInlineShortcodes = true
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  ShowRssButtonInSectionTermList = true
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    # limit = 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys = ["title", "content"]    